### PR TITLE
Attempt at automating code command installation

### PR DESCRIPTION
**Pull request by cytronicoder**
Add proposed automated `code` command installation to #825

### CODE REVIEW

**Comment by malted** [comment]
I'm quite confused why there's so much code - https://code.visualstudio.com/docs/setup/mac reckons this is all you need?
```bash
cat << EOF >> ~/.zprofile
# Add Visual Studio Code (code)
export PATH="\$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
EOF
```

**Comment by malted** [comment]
Have you seen https://code.visualstudio.com/docs/setup/mac#:~:text=Launch%20VS%20Code.,code'%20command%20in%20PATH%20command.?

**Comment by malted** [comment]
I would prefer to echo an `export PATH` into `~/.zprofile` than create a symlink!

**Comment by cytronicoder** [comment]
Just saw this - I'll check it out!

**Pull request merged**
