### PR TITLE
Confirm before deletion of project

### PR DESCRIPTION
**Pull request by Spectralo**
https://github.com/hackclub/high-seas/issues/718

### CODE REVIEW

**Comment by maxwofford** [comment]
Try it out on the preview build! https://high-seas-idhtpmxoh.hackclub.dev/shipyard. Make sure to use a new test project, because the confirm didn't work for me and just immediately deleted the project.

**Comment by Spectralo** [comment]
strange ... it shows the dialog but closes instantly

**Comment by Spectralo** [comment]
@maxwofford i fixed smth in my code, should work now, can you approve the deployment ?

**Comment by polytroper** [comment]
@Spectralo make sure you are using prettier. Install the extension and then format all the files you have changed. We are enforcing style consistency now that there are so many more people contributing

thanks!

**Comment by polytroper** [comment]
@Spectralo I just tested the latest version and it still seems to close the dialog instantly. Seems like clicking delete ship also somehow triggers the save button?

**Comment by Spectralo** [comment]
really ? strange ? checking that real quick

**Comment by Spectralo** [comment]
auth doesnt work :/

**Comment by Spectralo** [comment]
image

**Comment by maxwofford** [comment]
@Spectralo added! try now

**Comment by malted** [comment]
Hey! Thank you sm for your help - I fixed the issues and realised that we don't actually use the shadcn dialogue component anywhere, https://github.com/hackclub/high-seas/pull/757 uses `components/ui/modal` instead of it.

**Pull request closed without merging**
