### PR TITLE
Added field to the shipping form to set for_ysws in airtable

### PR DESCRIPTION
**Pull request by BudzioT**
- Added field to the shipping form to set for_ysws in airtable
- Also disabled it for tutorial
- Made updates take for_ysws from the previous ship in chain

None as default: 
image
image

YSWS chosen:
image
image

### CODE REVIEW

**Comment by malted** [comment]
Amazing work - testing now

**Comment by maxwofford** [comment]
Nice! A couple text changes here:
- "YSWS Contest" -> "Was this created for a YSWS program? (optional)"
- "Boba" -> "Boba Drops"

**Comment by BudzioT** [comment]
Updated as requested
image

**Comment by malted** [comment]
Created a ship with type onboard, and it appeared in Airtable! LGTM :)
image

**Pull request merged**
