### PR TITLE
Solves the style issue on the shop page. 

### PR DESCRIPTION
**Pull request by Gitstar-OC**
This will solve #839. I have commented the words which take more space.

### CODE REVIEW

**Comment by maxwofford** [comment]
Seems like #839 is closed, so I'm closing this PR!

**Comment by Gitstar-OC** [comment]
No, I closed this pr as this solves that. The issue was created by me.

**Comment by Gitstar-OC** [comment]
Please merge it.

**Comment by maxwofford** [comment]
Oh! I misread– in the future please close issues only once the PR is merged and you confirm the issue doesn't exist in prod anymore!

**Comment by Gitstar-OC** [comment]
Yes the issue is solved now closing the issue. :)

**Pull request merged**
