### PR TITLE
feat: commit hash

### PR DESCRIPTION
**Pull request by NeonGamerBot-QK**
feat: commit hash
note: please test this, im using it in env for now.

### CODE REVIEW

**Comment by maxwofford** [comment]
This is such a nice feature! Fix your formatting, then let's try to make it a little more pretty:

Screenshot 2024-11-22 at 07 12 44

Screenshot 2024-11-22 at 07 11 54

**Comment by maxwofford** [comment]
Heads up, it seems like you're fixing formatting manually and it doesn't follow the styles of the repo– let the repo handle it's own formatting! run `bun fmt`!

**Comment by maxwofford** [comment]
Also, don't worry about updating the branch– that just creates a bunch of merge commits in the history that aren't needed because you'll be merging this to main anyways.

**Comment by NeonGamerBot-QK** [comment]
@maxwofford linted!

**Pull request merged**
