### PR TITLE
Update edit-ship-form.tsx to add delete prompt to user

### PR DESCRIPTION
**Pull request by kokojkj**

### CODE REVIEW

**Comment by scooterthedev** [comment]
Hi! This code seems to have removed all the edit options besides for the delete section. We still need to user to be able to edit there ship form, not just delete it ;)

**Comment by kokojkj** [comment]
how to use Vercel  to see if it running correctly ?

**Comment by scooterthedev** [comment]
> how to use Vercel  to see if it running correctly ?

The way the system works I believe is that it will only work once deployed from them ie. Merged. Try fixing the code to the best of your ability and then someone from HC will look it over to make sure it will work before merging to main. Also just a side note, if you want to set it to a draft PR until the code is ready to be reviewed by HC that would help a lot and remove possible confusion on why a pr is half done!

**Comment by scooterthedev** [comment]
> how to use Vercel  to see if it running correctly ?

The way the system works I believe is that it will only work once deployed from them ie. Merged. Try fixing the code to the best of your ability and then someone from HC will look it over to make sure it will work before merging to main. Also just a side note, if you want to set it to a draft PR until the code is ready to be reviewed by HC that would help a lot and remove possible confusion on why a pr is half done!

**Comment by maxwofford** [comment]
This PR just deletes a file and has no additions.

**Comment by kokojkj** [comment]
Iam just messing around and try to fix if i can sorry for time wasting my bad

**Pull request closed without merging**
