### PR TITLE
prettify everything

### PR DESCRIPTION
**Pull request by polytroper**
now that we've open-sourced this thing…

we must prettify it now before it becomes impossible.

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/\[tab\]**](https://high-seas-81xhza96k.hackclub.dev/[tab]) | [**/**](https://high-seas-81xhza96k.hackclub.dev/) |
|:-:|:-:|
|<a href="https://high-seas-81xhza96k.hackclub.dev/[tab]">Screenshot of /[tab]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/BO4ohdJvEFemZQ85p9v1eh4cmB7_gHSAKXd_FCTZcFAK78Cat7kP06B8jRUTrGaWAcy9L-h1cAcjZGaeK2Shlg.png">(view full size)</a> |<a href="https://high-seas-81xhza96k.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/DiZ9V7TZ8j4pScR6ni3g5EIBQlieNMWFkAeRSU8OPSnIQi2UhEnxKtwdy2S-0XNP-faot9hobPJ1uTmhJU_Ieg.png">(view full size)</a> |



| [**/marketing**](https://high-seas-81xhza96k.hackclub.dev/marketing) | [**/slack-error**](https://high-seas-81xhza96k.hackclub.dev/slack-error) |
|:-:|:-:|
|<a href="https://high-seas-81xhza96k.hackclub.dev/marketing">Screenshot of /marketing</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/pAO3lPpCWAODtsQ8-3bKCVZHEkDZ4pxaNQ2uDJ0LyLjEszFIQ8M-hON7rr7TC19yiDSLG9gS_iT1YehytYayJA.png">(view full size)</a> |<a href="https://high-seas-81xhza96k.hackclub.dev/slack-error">Screenshot of /slack-error</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/gaV_B3MMdDb0YEs7c5VXz25vhrOxRepNLSeCi33dvNxM-O4-EXFv9ZRLtmrJsHYYc3mwqSQ98-QuYZE27lA5PA.png">(view full size)</a> |







Commit 185f76b92173258163e1039bdf542b74418e8444 (https://high-seas-81xhza96k.hackclub.dev).

**Review by NeonGamerBot-QK — APPROVED** [review]
pretty

**Comment by polytroper** [comment]
thanks dad 😭

**Comment by polytroper** [comment]
image

lol

(fixed)

**Review by NeonGamerBot-QK — APPROVED** [review]

**Pull request merged**
