### PR TITLE
add report interface

### PR DESCRIPTION
**Pull request by HubertKr4jnik**
added a project report interface to wonderdome

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
um ur code removes curses and blessings.

**Comment by HubertKr4jnik** [comment]
Oh. I thought it got pulled from High Seas. Will fix it later today

**Comment by maxwofford** [comment]
Screenshot 2024-12-08 at 22 03 11
This is a good start for the functionality, but it's kinda hard to tell that's a report button (esp when high seas is pirate themed). Check out how HCB does this! Or github itself!

**Comment by maxwofford** [comment]
Screenshot 2024-12-08 at 22 07 00
Ah, I'd also like to change the copy and actions here. It should say "Flag something about PROJECT NAME" with a list of options:

- Notify creator of invalid README
- Notify creator of invalid screenshot
- Notify creator of invalid demo link
- Flag for fraud...

If the user clicks one of the notify buttons, it pops up a confirm box saying "we'll send an anonymous notice to the creator you had problems with their README. continue?"

If the user clicks "flag for fraud" they get a prefilled link that takes them to a page for making the report– Ideally we don't need to code the flaging form ourselves.

**Comment by malted** [comment]
Hey! Thank you so much for this :)
Thanks to your help with this, we shipped a report feature in https://github.com/hackclub/high-seas/pull/945. Keep up the great work :D

**Comment by HubertKr4jnik** [comment]
Hi. Thanks for the info!

**Pull request closed without merging**
