### PR TITLE
feat: add opt in out functionality for the leaderboard

### PR DESCRIPTION
**Pull request by taciturnaxolotl**

### CODE REVIEW

**Review by Gitstar-OC — COMMENTED** [review]
Are you working on the leaderboard. Yay, thanks for accepting my suggestion. : )

**Comment by Cyteon** [comment]
I am making it :D

**Comment by Gitstar-OC** [comment]
> Im the one making it :D

Are you on the team too ? @Cyteon

**Comment by Cyteon** [comment]
Nope

**Comment by Cyteon** [comment]
> > Im the one making it :D
> 
> Are you on the team too ? @Cyteon

No, but im bored

**Pull request merged**
