### PR TITLE
feat | remove scrollbar on shipyard

### PR DESCRIPTION
**Pull request by Lazylllama**
I did this change on the web and found the fix using inspect- Please check the preview before merging 🙂

### CODE REVIEW

**Comment by malted** [comment]
image

Appl err

**Comment by Lazylllama** [comment]
Should be fixed!

**Comment by Lazylllama** [comment]
There is no way.

**Comment by malted** [comment]
Wait lowkey I'm confused what this is supposed to be doing - the scrollbar is still there?
image

Here too
image

Am I missing something?

**Comment by Lazylllama** [comment]
Well it took 3 weeks, so the UI has changed so much it doesnt apply anymore. Closing this.

**Pull request closed without merging**
