### PR TITLE
Disables clicking on dino when the idea is generating. 

### PR DESCRIPTION
**Pull request by Gitstar-OC**
Pointer is set to none when the idea is loading (getting generated) so the user will be able to click on the dino again only when the idea is generated. 

Also the price of framework laptop is changed to 4980 Doubloons on the homepage. 

This will solve #808. 

**Note**: I have not checked it by entering openai api keys but it works, please try check or deploying to preview before merging!

### CODE REVIEW

**Comment by Gitstar-OC** [comment]
@NeonGamerBot-QK Could you deploy it so I can see preview ? If you are here.

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/marketing**](https://high-seas-bkd9xugps.hackclub.dev/marketing) |
|:-:|
|<a href="https://high-seas-bkd9xugps.hackclub.dev/marketing">Screenshot of /marketing</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/XpnwsdqbvgVNB1cJtkJLXho_7wH4SEqSp7u3on-s-mqHiAbXaV3c8oVVYinSiNvO9kkA1gGApccKtTaSavsaPA.png">(view full size)</a> |







Commit c044cc8a12db35d1ea1ba8715df540291b36e87a (https://high-seas-bkd9xugps.hackclub.dev).

**Comment by Gitstar-OC** [comment]
Thanks @lachlanjc. @maxwofford ready for merge! 

Is there a way I can deploy to preview ?

**Comment by maxwofford** [comment]
@Gitstar-OC: that @/lachlanjc message is a bot!

I just approved deployment– test it out yourself and ping me if it works!

**Comment by Gitstar-OC** [comment]
Yes it works @maxwofford

**Comment by NeonGamerBot-QK** [comment]
> @NeonGamerBot-QK Could you deploy it so I can see preview ? If you are here.

i dont have vercel access fyi

**Comment by maxwofford** [comment]
@Gitstar-OC we can talk about it in slack! I'm merging this for now but heads up that you included [other changes](https://github.com/hackclub/high-seas/pull/817/files#diff-419e45faafa217e43f683c101d503ae716080c77ce35baf0c30556ef4e68fe0fL1209) in this PR! In the future please split them into separate PRs!

**Pull request merged**
